services:
  db:
    image: postgres:13-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    volumes:
      - ./db_data:/var/lib/postgresql/data